"""
Django settings for build_manage project.

Generated by 'django-admin startproject' using Django 1.9.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&((c8yx&95helm46=+)063&p13$!5z^pmhra(75^iat8k5p&+n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ATOMIC_REQUESTS = False

ALLOWED_HOSTS = ['10.10.10.241']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'build',
    'django_tables2',
    'django_nvd3',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'crum.CurrentRequestUserMiddleware',
]

ROOT_URLCONF = 'build_manage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'build_manage.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'OneClickUpdate_django',
		'HOST': '10.10.10.237',
        'USER': 'root',
        'PASSWORD': 'Admin@123',
        'CONN_MAX_AGE':0,
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
LOGIN_REDIRECT_URL = '/admin/'
PYTHON_SCRIPT = "/script/"
"""
JENKINS_URL = 'http://10.10.10.241:8080/'
JENKINS_USER = 'omkar'
JENKINS_PASS = 'omkar'
"""
JENKINS_URL = 'http://10.10.10.237:8080'
JENKINS_USER = 'omkar'
JENKINS_PASS = 'omkar'
"""
OCD_URL = '10.10.10.236'
OCD_USER = 'root'
OCD_PASS = 'root'
OCD_DB = 'build_manage'
"""

OCD_URL = '10.10.10.237'
OCD_USER = 'root'
OCD_PASS = 'Admin@123'
OCD_DB = 'OneClickUpdate'
#OCD_DB = 'oneclickupdate_empty'
#ReadOnlyUser
ROCD_USER = 'root'
ROCD_PASS = 'Admin@123'


"""
OCD_URL = '10.10.11.23'
OCD_USER = 'manoj'
OCD_PASS = 'pass'
OCD_DB = 'OneClickUpdate'
"""

"""
OCD_URL = '10.10.10.241'
OCD_USER = 'root'
OCD_PASS = 'root'
OCD_DB = 'OneClickUpdate'
"""


#BuildDB configaration paratmers
BUILDDB_RUNSCRIPT = 'D:\\python34\\python.exe D:\\web\\oneClickUpdate\\script\\get_releaseable_pkg.py'
BUILDDB_HOSTNAME = '10.10.3.176'
BUILDDB_USERNAME = 'manoj'
BUILDDB_PASSWORD = 'pass'
BUILDDB_DATABASE = 'jenkins'

#Verify Release
RELEASE_SERVER_PATH = "http://10.10.11.55/test_server"
VERIFY_RELEASE_PATH = "./script/verify_release"
RELEASE_PACKAGE_LIMIT = 100

#API configaration paratmers
API_RUNSCRIPT = 'D:\\python34\\python.exe D:\\web\\oneClickUpdate\\script\\test.py'
API_HOSTNAME = '10.10.3.176'
API_USERNAME = 'manoj'
API_PASSWORD = 'pass'
API_DATABASE = 'jenkins'



TIME= 30*60
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'
SESSION_EXPIRE_AT_BROWSER_CLOSE= True
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_AGE = TIME
SESSION_IDLE_TIMEOUT = TIME
DEBUG_PRINT = 1



#DOWNLOAD_BUILD_PATH = 'http://file://///10.10.8.177/build_server/'
#AUTOMATION_FLAG = 0
#AUTOMATION_USER = 'automation'
#AUTOMATION_FILE_PATH = "//10.10.10.237/kamesh-web/temp\Test_File\Automation_Testing_File.txt"

#